### ISSUE TITLE
第一章翻译讨论

### ISSUE THREAD

**Issue by tsukishima1321** [kono-dada/Sakuranotoki-Chinese#1]
**01_01:**

直哉「这是什么问题！？」「そんな問題！？」
-> 「重点是这个吗！？」/「是为了这个吗！？」

静流「虽然今天是重新开张的第一天，但你还是经常来店里呢」「今日は再開した初日だけど、良く来店してくれたね」
虽然今天是重新开张的第一天，（但你还是来了，看来）你经常来店里呢
-> 「今天可是重新开张的第一天，看来你经常来店里呢」

静流「所以你在做那种咨询工作吗。我在这家店里使用了各种不同的豆子，嗯，就像是市场调研一样。所以你可以喝到一些非常便宜且罕见的咖啡」「そういうコンサル的な仕事をしていた。このキマイラではいろいろな豆を送って使ってもらっていたが、まぁ、市場調査みたいなもんだね。だから通常よりも格安でめずらしいコーシーが飲める」
-> 「我就在做那种…类似咨询的工作。这家店里用了各种不同的豆子，嗯，就像是市场调研一样。所以你可以喝到一些非常便宜且罕见的咖啡」

直哉「如果是上课的话，我下午没什么问题。因为下午都是美术课，不用急着赶回去」「授業なら問題ありませんよ。午後から美術の授業なんてありませんから」
-> 「上课的话没有问题，因为从下午开始就没有美术课了」

他比我们两个人想象的要与夏目有更深的关系。彼が思う以上に私と夏目の人間は関係が深い。
-> 我和夏目家的关系比他想象的要深。

**01_02_1:**

丽华「这不是问题。你是我们的一员，你应该随时都穿着整洁的制服」「そういう問題ではありません。あなたは我々の一族なのですから、いつでもパリっとノリの利いた制服を着て頂かないとなりません」
-> 「不是这种问题。你是我们的一员，你应该随时都穿着整洁的制服」

**01_02_2:**

后来可以随便说谁错了，这是错的，把谁塑造成坏人也是容易的。誰が悪かった、これが悪かった、なんて事は後からならいくらでも言える。誰かを悪者に仕立てる事だって容易い。
-> 那个人错了，这件事错了，这种话在事后多少都能说出来。把谁塑造成坏人也是容易的。

**01_02_3:**

静流
「没关系的，没关系的，我在这个学校里有些特殊待遇。这里的教头，叫做中村纱希，是我阿姨」
教头 -> 副校长 

**01_02_4:**

丽华「我是中村丽华。我们中村被你们夏目抹黑的人」
->「我是中村丽华。被你们夏目抹黑的中村的人」

**01_02_5:**

纱希「嗯，我很不喜欢她。虽然她只是个小女孩，但她就像个唠叨的小姑娘」「ああ、私は彼女が大の苦手だ。小娘なのにかなり小姑だ」
-> 「嗯，我很不喜欢她。明明只是个小女孩，却像个小姑」

**01_03_1:**

静流「丽华是！？」「麗華は！？」
-> 「丽华…！？」

**01_03_2：**

静流「能不能让我见见真琴呢？」-> 静流「能不能让他见见真琴呢？」 

丽华「所以我说过。圭不是杂种。她是纯血统」「她对我一点也不屈服。
确实，那种毅力不是一般人能有的」「但是，我之前不知道这个事实，只觉得她是个无礼的孩子」
她 -> 他 

**01_03_3:**

感觉有点奇怪……或者说有点鱼腥……。なんか怪しいというか……胡散臭いというか……。
-> 感觉有点奇怪……或者说有点可疑……。 

**01_04_2:**

我并未收到任何回复，因此我准备了超过三百万日元的物品。然后我重新发送了。まったく連絡が返って来なかったので、三百万円以上のものを用意した。と再送した。
->因为没有收到任何回复，我再发送了一次，并且表示我准备了超过三百万日元的物品。

**01_04_3：**

静流「那么，已经没学生的时间了，我们现在就看看吧？」「それじゃ、生徒もいなくなる時間ですし、そろそろ見せましょうか？」
->「那么，已经是没有学生的时间了，我们现在就看看吧？」/「那么，学生们都走了，我们现在就看看吧？」

**01_04_4:**

健一郎「啊，是沙纪的侄女吗？我是草薙健一郎。请多关照。」
纱纪->纱希

**01_05:**

静流「如果丽华把那个东西拿给别人看，会让他们丢脸的！」-> 「如果丽华把那个东西拿给别人看，你会丢脸的！」

**本条中所有修改已merge**

**Comment by kono-dada** [comment]
倒是可以对这几句话进行修改，但是类似的问题后面可能依旧存在。该怎么办呢

**Comment by tsukishima1321** [comment]
机翻不准确没办法，小一点的错误要很强的日语能力才能校对出来，就算是明显的错误也容易漏。我也就是看一点记一点，供后人参考吧，没有专业又多的人手没法做很多事。

**Comment by tsukishima1321** [comment]
01_02_04:
丽华「我不管你的社团怎么样！」「あ、あなたの部活がどうなっても知らないわよ！」
男生在社团活动上有求于丽华 这句话应该是表示威胁、强调社团来胁迫他们继续帮忙 不是很能拿定怎么翻才好

**Comment by kono-dada** [comment]
“你的社团会变成什么样，我可说不准哦”

**Comment by tsukishima1321** [comment]
**01_02_5：**

主人
「嗯，或多或少的，在以自由为校风的名门学校，似乎有这样的事情发生。但是，圣路安学园这样的名门学校应该是没有的」
「まぁ、多かれ少なかれ、自由を校風にした名門学校ではそういう事が行われていた様だよ。さすがに、同じ弓張の名門である聖ルーアン学園ではなかっただろうけど」
-> 「嘛，以自由为校风的名门学校，似乎或多或少都有这样的事情发生。但是，同样是弓张名门的圣卢安学园应该是没有的」

**01_03_2:**

丽华「圭是天才画家宫崎破戒的孙女」
->「圭是天才画家宫崎破戒的孙子」

丽华「真让人吃惊。竟然，那个孩子是天才画家的孙女」
-> 「真让人吃惊。竟然，那个孩子是天才画家的孙子」

丽华「是那个女人的事，也许她正在进行内部调查吧？从一开始就知道了什么，所以才接触恩田雾乃」
麗華「あの女の事だから、内偵を進めていたんじゃないかしら？最初っからなにかしら知っていた、だからこそ恩田霧乃と接触した」
-> 「既然是那个女人的话，应该在进行内部调查吧？从一开始就知道了什么，所以才接触恩田雾乃」

那时，他已经被誉为神童、天才、绘画之子。他的名字是草薙直哉。
当時、すでに神童、天才、絵画の子と称されていた少年がいた。その名は草薙直哉。
-> 那时，还有一个已经被誉为神童、天才、绘画之子的少年。他的名字是草薙直哉。

**01_03_3:**

静流「阿姨你知道圭的血统，却对中村家的人保持沉默。而且，你还让圭去了你的熟人宮崎画学校」
静流「おばさんは圭の血筋を知っていて、中村の人間に黙っていた。そして、ゆかりでもある宮崎絵画学校に圭を通わせた」
-> 「阿姨你知道圭的血统，却对中村家的人保持沉默。而且，你还让圭去了和你有关系的宮崎画学校」

宮崎絵画学校、宫崎画校、宮崎画学校、宫崎美术学校 ->宫崎绘画学校

**Comment by UnCLAS-Prommer** [comment]
01_04_2:
```
{"静流":"「なんか、少し雰囲気変わったね」"},
{"麗華":"「どこが？」"},
{"静流":"「なんだろ、いまだって、前だったら『なにがですの？』みたいな返しだった様な」"},
```
这个地方怎么翻译才能体现出这个气质变化
