### ISSUE TITLE
第三章

### ISSUE THREAD

**Issue by tsukishima1321** [kono-dada/Sakuranotoki-Chinese#13]
**03_02_1:**

如果是50号的话，一边就超过了一米，即使是周末画家，这个尺寸也足够大了。
50号ならば一辺が一メートルを超えるので、これでも日曜画家ならば十分にもてあます巨大なサイズだ。
->如果是50号的话，一边就超过了一米，对业余画家来说这个尺寸称得上是巨大了。

直哉「不，那个数字少了一个零。确实，我听说超过了一百万日元」
直哉「いや、それ一桁間違っている。たしかに、百万円は超えたらしいけど」
-> 直哉「不，那个数字差了一位。确实，我听说超过了一百万日元」

直哉「我并没有恶意。生活为艺术家真的很辛苦。我这种人很快就会露馅，在十年内就会没法过活」
直哉「嫌味じゃないよ。芸術家で食っていくのは大変なんだよ。俺なんかすぐメッキがはがれて十年もしないうちに食いっぱぐれる」
-> 直哉「我并没有恶意。靠做艺术家来生活真的很辛苦。我这种人很快就会露馅，在十年内就会没法过活」

**03_04_5:**

直哉「啊，那些卖不出去的东西是静流小姐恶作剧做的赝品吗？」
直哉「ああ、あの売れないものって、静流さんのいたずらで作った贋作なのですか？」
-> 直哉「啊，那个买不到的东西是静流小姐恶作剧做的赝品吗？」

**03_04_6**

铃菜「是的，校长说，通过使用那个地方，他获得了远远超出其价值的回报，所以即使只是小小的投资，也绝对没有损失。这就是他的回答」
鈴菜「はい、なんでも、あの場所を使うことによって、それに見合うどころではないものが手に入ったのだから、わずかながらでも投資して損はないだろう？だそうです」
-> 铃菜「是的，校长说，通过使用那个地方，获得了很大的回报，为此做一些相比起来小小的投资也不亏吧？这就是她的回答」

**03_04_7:**

因为，只有Lain这样的人才会做那种事。
だって、そんなもの、Lainレインくらいしかやっていないのだもの。
-> 因为，那样的东西除了Lain我也没有碰过别的。

**Comment by tsukishima1321** [comment]
**03_06_1:**

「猫的数量」和「很多」这样的日语用法实在是太奇怪了。
「猫の方」だったり「いらっしゃったり」とめちゃくちゃな日本語だなぁ。
……
「猫的方」已经升级成「猫大人」了。
「猫の方」から「猫さま」に格上げになっているよ。

这个涉及到敬语的问题……

直哉「嗯，这附近的猫咪都已经习惯了人。根据季节的不同，它们甚至会在没有被叫唤的情况下，用猫的语气主动靠近」
直哉「ああ、ここいらの猫は人に馴れているからな。季節によっては頼まれもしないであちらから猫なで声で近づいてくる」

直哉「好吃好吃，就保持这样不动，不要和它对视，等待」
直哉「うまいうまい、そのまま動かず、目を合わせずに待機する」
-> 直哉「做得好，就保持这样不动，不要和它对视，等待」

**Comment by kono-dada** [comment]
{"心鈴": "「哇！这里有好多猫先生光临此地呀」"},
{"旁白": "「猫先生」和「光临」这样的日语用法实在是太奇怪了。"},

「猫先升」已经升级成「猫大人」了。

可以这样翻译

**Comment by tsukishima1321** [comment]
**03_mis05_3:**
奈津子
「年纪轻轻就多次获奖的露莉莴小姐，以及最近刚刚在FIRST展获得
最高奖的宁小姐。入选文展三科展以及穆尔展的草薙老师，而且在
他们当中也有世界级的艺术家，曾获得Le
Salon等世界级奖项的宫崎心铃老师」

游戏里最多显示三行，这句话就放不下了……

**Comment by tsukishima1321** [comment]
**03_mak03_2:**
直哉「吉泽老师，看了这个你怎么看？“在弟子中最优秀的”这样的闲话，你还说得出口吗」
直哉「吉沢先生、これ見てどう思うかね。“弟子の中でもっとも”優れたとか、悠長な事言ってられるかなぁ」
